title : Friendsforturner
description: "Your State Representative from Illinois' 9th Legislative District"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
